name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Sync dependencies (dev, frozen)
        run: uv sync --all-extras --dev --frozen

      - name: Run checks
        run: make check
  tests-and-type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync --all-extras --dev --frozen

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest || (echo "No tests found" && exit 0)

      - name: Check typing
        run: uv run mypy trilogy || echo "Type checking completed with warnings"
